# Generated by Django 6.0 on 2026-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workspacemember',
            options={'managed': False},
        ),
    ]
