# Generated by Django 6.0 on 2026-01-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_board_alter_project_options_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='workspace',
            table='workspace',
        ),
        migrations.AlterModelTable(
            name='workspacemember',
            table='workspace_member',
        ),
    ]
